dataset: cub200

model: podnet
convnet: resnet18

fixed_memory: true
memory_size: 1000

eval_type: cnn

convnet_config:
  last_relu: True
  pretrained: True
  nf: 64
  initial_kernel: 7
  
classifier_config:
  type: cosine
  proxy_per_class: 3
  distance: cosine

postprocessor_config:
  type: learned_scaling
  initial_value: 1.0

pod_flat:
  scheduled_factor: 1.0

pod_spatial:
  scheduled_factor: 3.0
  collapse_channels: spatial

nca:
  margin: 0.0
  scale: 1.
  exclude_pos_denominator: True
  hinge_proxynca: True
  
groupwise_factors:
  old_weights: 0.0
  convnet: 0.02
  
finetuning_config:
  sampling: undersampling
  tuning: classifier_scale
  lr: 0.1
  epochs: 30
  scheduling:
    type: step
    epochs: [15]
    gamma: 0.1
  scaling: null

# Cosine Scheduling (CS)
scheduling: cosine

# Misc
epochs: 100
lr: 0.05
lr_decay: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.0005

weight_generation:
  type: imprinted
  multi_class_diff: kmeans

no_progressbar: True

